# ===================================================================
# FS PKO8  Spring Cloud Config.
# ===================================================================

# Property used on app startup to check the config server status
configserver:
    name: JHipster PKO8 Registry config server
    status: Connected to the JHipster Registry config server, using https://github.com/abhisheksharma85/pko8-registry-config !

# Default JWT secret token (to be changed in production!)
jhipster:
    security:
        authentication:
            jwt:
                secret: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImp0aSI6IjllOGM5NWFlLWJiYzgtNDA2MC04MTBmLTk4ZmYwNzk1ZWRiNCIsImlhdCI6MTUxNTQ0MDkwMSwiZXhwIjoxNTE1NDQ0NTAxfQ.c1-4SotUhQN1603W2o_6IzR1IFN2bRxS1TPX0ahPDFM
